default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: lizard_development

test:
  <<: *default
  database: lizard_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") { "lizard_production" } %>
  cache:
    <<: *default
    database: <%= ENV.fetch("CACHE_DATABASE_NAME") { "lizard_production_cache" } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME") { "lizard_production_queue" } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("CABLE_DATABASE_NAME") { "lizard_production_cable" } %>
    migrations_paths: db/cable_migrate
